### PR TITLE
Migrate to Typescript + improvements

### PR DESCRIPTION
**Pull request by pepicrft**
I'm planning to use the project with my Jekyll blog and I took the opportunity to move the code to Typescript. I don't have much experience with Javascript & Typescript so let me know if there's anything that I can improve in the code.

Besides the migration to Typescript:
- I've added some tests.
- I've added support for reactions! Now each comment includes a all the reactions 👍 ❤️

### CODE REVIEW

**Comment by orta** [comment]
I really like this. It's a solid improvement, feels a bit like graphql-y where you're making it grab *all* the data and consolidating it at the point where it's fastest. 

Good job 👍 

I don't really have quibbles at the code other than it feels a little dense, but it's short, readable and understandable which are the most important things for me - this is solid work.

**Comment by orta** [comment]
Can't believe  I forgot comment pagination, it happens on every project I build.

**Comment by orta** [comment]
Added you as a contributor, no pressure to do anything ( I think you just 100%'d this project ) but at least you can feel like you can control your destiny

**Comment by pepicrft** [comment]
Oh thanks! I'll clean up the code a little bit because the combination of the promises returned by the `fetch` function is a bit messy. I wonder if there's any alternative to `node-fetch` that I can use that  returns another type of object that is easier to combine/manipulate. What do you think about [Bluebird](http://bluebirdjs.com/docs/getting-started.html)?

> Can't believe I forgot comment pagination, it happens on every project I build.

Oh, I think pagination is still not supported but I didn't think about it either. I think that's another improvement that I can add.

> Added you as a contributor, no pressure to do anything ( I think you just 100%'d this project ) but at least you can feel like you can control your destiny

Thanks for adding me as a contributor. It'll be easier to push branches and open PRs. Is it ok if I keep adding you as a reviewer?

By the way, as I mentioned I plan to add it to my Jekyll blog. I was thinking about using Webpack + React and componentize the implementation of the comments section. Since the comments are in Markdown, I wonder if you have used any parser to converts the markdown into HTML. If you have, do you mind if I ask you which one?

Thanks a lot!

**Comment by orta** [comment]
I use node-fetch everywhere, it comes with promise support - so you can use the `async` keyword to simplify a bunch of it, e.g. the API client in Danger JS:

https://github.com/danger/danger-js/blob/3060cb6880e79b5b29532c7d4f124b214b192a1f/source/platforms/github/GitHubAPI.ts#L79-L89

---

Yep, I'll always be available for reviewing code 👍 

I'm pretty sure these comments include html _or_ markdown, we use [html in the artsy blog](https://github.com/artsy/artsy.github.io/blob/78b05fbcc4e884b7d7ef00b0b2ed4f6e5a3fe960/_includes/gh_comments.html#L40-L67) so you shouldn't need to parse it

**Comment by orta** [comment]
Actually, this file is a better example: https://github.com/orta/misc_typescript_scripts/blob/master/get_all_repos.ts

**Comment by pepicrft** [comment]
Oh thanks! I completely forgot about async/await to use promises as if it was synchronous code. I think that will help a lot. Thanks @orta

**Pull request merged**
