### PR TITLE
Cleanup and pagination support

### PR DESCRIPTION
**Pull request by pepicrft**
I've cleaned up the implementation using `async/await`. Moreover, I've added support for pagination.

#### Checklist
- [x] Clean up implementation.
- [x] Add pagination support.
- [x] Test `parseLinkHeader`.
- [x] Test `github`.

### CODE REVIEW

**Comment by orta** [comment]
Yep - looking good!

**Comment by pepicrft** [comment]
Should be ready now @orta !

**Comment by orta** [comment]
Yep, this looks 👍 to me - nice work

**Comment by orta** [comment]
I've cleaned up the README, and given everything a one over in my editor - changes all look great, good job.

**Comment by pepicrft** [comment]
Awesome! I started using it on my blog as well. Very cool idea @orta

**Pull request merged**
